import type { Metadata } from "next";
import { Nunito } from "next/font/google"
import { CartProvider } from "@/providers/cartProvider"

import "./globals.css"
import { ReduxProvider } from "@/providers/reduxProvider"

const nunitoSans = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <CartProvider>
          <body className={`${nunitoSans.className}`}>{children}</body>
        </CartProvider>
      </ReduxProvider>
    </html>
  )
}
